# A workflow that checks that the debug options haven't bitrotted.
name: Compile with all debug options

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  all-debug-compile-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.13.0

      - name: Enable all debug flags
        run: scripts/enable-all-debug-flags.sh

      - name: Compile the project
        run: zig build
